// ============================================================
//  STEP 1: All City Store in Array
// ============================================================

// const cities = {
//   "pakistan": "pakistan",
//   "indian": "indian",

//   "Islamabad": "Islamabad",
//   "Karachi": "Karachi",
//   "Lahore": "Lahore",
//   "Peshawar": "Peshawar",
//   "Quetta": "Quetta",
//   "Multan": "Multan",
//   "Faisalabad": "Faisalabad",
//   "Rawalpindi": "Rawalpindi",
//   "Sialkot": "Sialkot",
//   "Gujranwala": "Gujranwala",
//   "New York": "New York",
//   "Los Angeles": "Los Angeles",
//   "Chicago": "Chicago",
//   "Houston": "Houston",
//   "Miami": "Miami",
//   "San Francisco": "San Francisco",
//   "Dallas": "Dallas",
//   "Seattle": "Seattle",
//   "Boston": "Boston",
//   "Las Vegas": "Las Vegas",
//   "London": "London",
//   "Manchester": "Manchester",

//   "Dubai": "Dubai", "Abu Dhabi": "Abu Dhabi", "Sharjah": "Sharjah", "Ajman": "Ajman",
//   "Paris": "Paris", "Lyon": "Lyon", "Marseille": "Marseille", "Nice": "Nice", "Toulouse": "Toulouse",
//   "Berlin": "Berlin", "Munich": "Munich", "Hamburg": "Hamburg", "Frankfurt": "Frankfurt", "Cologne": "Cologne",
//   "Tokyo": "Tokyo", "Osaka": "Osaka", "Kyoto": "Kyoto", "Hiroshima": "Hiroshima", "Sapporo": "Sapporo",
//   "Mumbai": "Mumbai", "New Delhi": "New Delhi", "Bangalore": "Bangalore", "Chennai": "Chennai", "Kolkata": "Kolkata",
//   "Istanbul": "Istanbul", "Ankara": "Ankara", "Izmir": "Izmir", "Bursa": "Bursa",
//   "Moscow": "Moscow", "Saint Petersburg": "Saint Petersburg", "Novosibirsk": "Novosibirsk",
//   "Beijing": "Beijing", "Shanghai": "Shanghai", "Guangzhou": "Guangzhou", "Shenzhen": "Shenzhen", "Chengdu": "Chengdu",
//   "Singapore": "Singapore", "Bangkok": "Bangkok", "Kuala Lumpur": "Kuala Lumpur", "Jakarta": "Jakarta", "Manila": "Manila",
//   "Sydney": "Sydney", "Melbourne": "Melbourne", "Brisbane": "Brisbane", "Perth": "Perth", "Adelaide": "Adelaide",
//   "Toronto": "Toronto", "Vancouver": "Vancouver", "Montreal": "Montreal", "Calgary": "Calgary", "Ottawa": "Ottawa",
//   "Cairo": "Cairo", "Alexandria": "Alexandria", "Giza": "Giza",
//   "Riyadh": "Riyadh", "Jeddah": "Jeddah", "Mecca": "Mecca", "Medina": "Medina",
//   "Seoul": "Seoul", "Busan": "Busan", "Incheon": "Incheon",
//   "Rome": "Rome", "Milan": "Milan", "Naples": "Naples", "Turin": "Turin", "Florence": "Florence",
//   "Madrid": "Madrid", "Barcelona": "Barcelona", "Valencia": "Valencia", "Seville": "Seville",
//   "Amsterdam": "Amsterdam", "Rotterdam": "Rotterdam", "The Hague": "The Hague",
//   "Hong Kong": "Hong Kong", "Macau": "Macau",
//   "Nairobi": "Nairobi", "Mombasa": "Mombasa",
//   "Lagos": "Lagos", "Abuja": "Abuja", "Kano": "Kano",
//   "Buenos Aires": "Buenos Aires", "Cordoba": "Cordoba", "Rosario": "Rosario",
//   "São Paulo": "São Paulo", "Rio de Janeiro": "Rio de Janeiro", "Brasilia": "Brasilia", "Salvador": "Salvador",
//   "Mexico City": "Mexico City", "Guadalajara": "Guadalajara", "Monterrey": "Monterrey",
//   "Colombo": "Colombo", "Kandy": "Kandy",
//   "Kathmandu": "Kathmandu", "Pokhara": "Pokhara",
//   "Dhaka": "Dhaka", "Chittagong": "Chittagong",
//   "Cape Town": "Cape Town", "Johannesburg": "Johannesburg", "Durban": "Durban", "Pretoria": "Pretoria",
//   "Casablanca": "Casablanca", "Rabat": "Rabat", "Marrakech": "Marrakech",
//   "Tehran": "Tehran", "Isfahan": "Isfahan", "Mashhad": "Mashhad",
//   "Baghdad": "Baghdad", "Basra": "Basra",
//   "Kabul": "Kabul", "Kandahar": "Kandahar",
//   "Accra": "Accra", "Kumasi": "Kumasi",
//   "Lima": "Lima", "Cusco": "Cusco",
//   "Bogota": "Bogota", "Medellin": "Medellin", "Cali": "Cali",
//   "Santiago": "Santiago", "Valparaiso": "Valparaiso",
//   "Lisbon": "Lisbon", "Porto": "Porto",
//   "Vienna": "Vienna", "Graz": "Graz",
//   "Zurich": "Zurich", "Geneva": "Geneva", "Basel": "Basel",
//   "Brussels": "Brussels", "Antwerp": "Antwerp", "Ghent": "Ghent",
//   "Stockholm": "Stockholm", "Gothenburg": "Gothenburg", "Malmö": "Malmö",
//   "Oslo": "Oslo", "Bergen": "Bergen",
//   "Copenhagen": "Copenhagen", "Aarhus": "Aarhus",
//   "Helsinki": "Helsinki", "Tampere": "Tampere",
//   "Warsaw": "Warsaw", "Krakow": "Krakow", "Lodz": "Lodz",
//   "Budapest": "Budapest", "Debrecen": "Debrecen",
//   "Prague": "Prague", "Brno": "Brno",
//   "Bucharest": "Bucharest", "Cluj-Napoca": "Cluj-Napoca",
//   "Athens": "Athens", "Thessaloniki": "Thessaloniki",
//   "Kyiv": "Kyiv", "Kharkiv": "Kharkiv", "Odessa": "Odessa",
//   "Minsk": "Minsk", "Brest": "Brest",
//   "Baku": "Baku", "Ganja": "Ganja",
//   "Tbilisi": "Tbilisi", "Batumi": "Batumi",
//   "Yerevan": "Yerevan", "Gyumri": "Gyumri",
//   "Tashkent": "Tashkent", "Samarkand": "Samarkand",
//   "Almaty": "Almaty", "Nur-Sultan": "Nur-Sultan",
//   "Doha": "Doha", "Al Wakrah": "Al Wakrah",
//   "Kuwait City": "Kuwait City", "Hawalli": "Hawalli",
//   "Amman": "Amman", "Zarqa": "Zarqa",
//   "Beirut": "Beirut", "Tripoli": "Tripoli",
//   "Damascus": "Damascus", "Aleppo": "Aleppo",
//   "Muscat": "Muscat", "Salalah": "Salalah",
//   "Colombo": "Colombo", "Negombo": "Negombo",
//   "Yangon": "Yangon", "Mandalay": "Mandalay",
//   "Phnom Penh": "Phnom Penh", "Siem Reap": "Siem Reap",
//   "Vientiane": "Vientiane", "Luang Prabang": "Luang Prabang",
//   "Hanoi": "Hanoi", "Ho Chi Minh City": "Ho Chi Minh City", "Da Nang": "Da Nang",
//   "Taipei": "Taipei", "Taichung": "Taichung", "Kaohsiung": "Kaohsiung",
//   "Auckland": "Auckland", "Wellington": "Wellington", "Christchurch": "Christchurch",
//   "Addis Ababa": "Addis Ababa", "Dire Dawa": "Dire Dawa",
//   "Dar es Salaam": "Dar es Salaam", "Dodoma": "Dodoma",
//   "Kampala": "Kampala", "Entebbe": "Entebbe",
//   "Kigali": "Kigali", "Butare": "Butare",
//   "Luanda": "Luanda", "Huambo": "Huambo",
//   "Kinshasa": "Kinshasa", "Lubumbashi": "Lubumbashi",
//   "Harare": "Harare", "Bulawayo": "Bulawayo",
//   "Lusaka": "Lusaka", "Ndola": "Ndola",
//   "Maputo": "Maputo", "Beira": "Beira",
//   "Antananarivo": "Antananarivo",
//   "Dakar": "Dakar", "Touba": "Touba",
//   "Abidjan": "Abidjan", "Yamoussoukro": "Yamoussoukro",
//   "Ouagadougou": "Ouagadougou", "Bobo-Dioulasso": "Bobo-Dioulasso",
//   "Bamako": "Bamako", "Timbuktu": "Timbuktu",
//   "Niamey": "Niamey", "Zinder": "Zinder",
//   "Ndjamena": "Ndjamena",
//   "Khartoum": "Khartoum", "Omdurman": "Omdurman",
//   "Mogadishu": "Mogadishu", "Hargeisa": "Hargeisa",
//   "Djibouti City": "Djibouti City",
//   "Asmara": "Asmara",
//   "Lilongwe": "Lilongwe", "Blantyre": "Blantyre",
//   "Windhoek": "Windhoek", "Walvis Bay": "Walvis Bay",
//   "Gaborone": "Gaborone", "Francistown": "Francistown",
//   "Maseru": "Maseru",
//   "Mbabane": "Mbabane",
//   "Monrovia": "Monrovia",
//   "Freetown": "Freetown",
//   "Conakry": "Conakry",
//   "Bissau": "Bissau",
//   "Banjul": "Banjul",
//   "Nouakchott": "Nouakchott",
//   "Havana": "Havana", "Santiago de Cuba": "Santiago de Cuba",
//   "Santo Domingo": "Santo Domingo",
//   "Port-au-Prince": "Port-au-Prince",
//   "Kingston": "Kingston", "Montego Bay": "Montego Bay",
//   "San Jose": "San Jose", "Alajuela": "Alajuela",
//   "Guatemala City": "Guatemala City",
//   "Tegucigalpa": "Tegucigalpa", "San Pedro Sula": "San Pedro Sula",
//   "Managua": "Managua", "Leon": "Leon",
//   "San Salvador": "San Salvador",
//   "Panama City": "Panama City",
//   "Caracas": "Caracas", "Maracaibo": "Maracaibo",
//   "Quito": "Quito", "Guayaquil": "Guayaquil",
//   "La Paz": "La Paz", "Santa Cruz": "Santa Cruz",
//   "Asuncion": "Asuncion", "Ciudad del Este": "Ciudad del Este",
//   "Montevideo": "Montevideo", "Salto": "Salto",
//   "Georgetown": "Georgetown",
//   "Paramaribo": "Paramaribo",
//   "Cayenne": "Cayenne",
//   "Reykjavik": "Reykjavik",
//   "Dublin": "Dublin", "Cork": "Cork", "Galway": "Galway",
//   "Edinburgh": "Edinburgh", "Aberdeen": "Aberdeen",
//   "Cardiff": "Cardiff", "Swansea": "Swansea",
//   "Valletta": "Valletta",
//   "Nicosia": "Nicosia", "Limassol": "Limassol",
//   "Riga": "Riga", "Daugavpils": "Daugavpils",
//   "Vilnius": "Vilnius", "Kaunas": "Kaunas",
//   "Tallinn": "Tallinn", "Tartu": "Tartu",
//   "Chisinau": "Chisinau", "Balti": "Balti",
//   "Tirana": "Tirana", "Durres": "Durres",
//   "Skopje": "Skopje", "Bitola": "Bitola",
//   "Sarajevo": "Sarajevo", "Banja Luka": "Banja Luka",
//   "Belgrade": "Belgrade", "Novi Sad": "Novi Sad",
//   "Zagreb": "Zagreb", "Split": "Split",
//   "Ljubljana": "Ljubljana", "Maribor": "Maribor",
//   "Bratislava": "Bratislava", "Kosice": "Kosice",
//   "Podgorica": "Podgorica", "Niksic": "Niksic",
//   "Pristina": "Pristina", "Prizren": "Prizren",
//   "Sofia": "Sofia", "Plovdiv": "Plovdiv",
//   "Ankara": "Ankara", "Bursa": "Bursa",
//   "Ulaanbaatar": "Ulaanbaatar",
//   "Pyongyang": "Pyongyang",
//   "Thimphu": "Thimphu",
//   "Male": "Male",
//   "Kathmandu": "Kathmandu",
//   "Colombo": "Colombo",
//   "Nuku'alofa": "Nuku'alofa",
//   "Suva": "Suva",
//   "Port Moresby": "Port Moresby",
//   "Honiara": "Honiara",
//   "Port Vila": "Port Vila",
//   "Apia": "Apia","saudi arabia":"saudi arabia","Qatar":"Qatar","kamalia":"kamalia"
//   ,"china":"china","japan":"japan","turkey":"turkey","russia":"russia"
//   ,"france":"france","germany":"germany","italy":"italy","spain":"spain","netherlands":"netherlands"
//   ,"switzerland":"switzerland","belgium":"belgium","sweden":"sweden","norway":"norway","denmark":"denmark"
//   ,"finland":"finland","poland":"poland","hungery":"hungary","czech republic":"czech republic","romaina":"romaina"
//   ,"greece":"greece","ukraine":"ukraine","belarus":"belarus","azerbaijan":"azerbaijan","georgia":"georgia"
//   ,"thiland":"thiland","singapore":"singapore","malaysia":"malaysia","indonesia":"indonesia","philippines":"philippines",
//   "australia":"australia","new zealand":"new zealand","ethiopia":"ethiopia","tanzania":"tanzania","uganda":"uganda","rwanda":"rwanda",
//   "angola":"angola","balochistan":"balochistan","sindh":"sindh",
//   "punjab":"punjab","philistine":"philistine","afghanistan":"afghanistan","bangladesh":"bangladesh","sri lanka":"sri lanka",
//    "myanmar":"myanmar","cambodia":"cambodia","laos":"laos","vietnam":"vietnam","taiwan":"taiwan","new zealand":"new zealand",
//    "ethiopia":"ethiopia","tanzania":"tanzania","uganda":"uganda","rwanda":"rwanda","mozambique":"mozambique",
//    "botswana":"botswana","lesotho":"lesotho","swaziland":"swaziland","zimbabwe":"zimbabwe","namibia":"namibia",
//    "gabon":"gabon","congo":"congo","sudan":"sudan","somalia":"somalia","djibouti":"djibouti","eritrea":"eritrea",
//    "malawi":"malawi","mauritius":"mauritius","seychelles":"seychelles","comoros":"comoros","cape verde":"cape verde",
//    "guinea":"guinea","guinea-bissau":"guinea-bissau","gambia":"gambia","mauritania":"mauritania","liberia":"liberia",
//    "sierra leone":"sierra leone","ivory coast":"ivory coast","burkina faso":"burkina faso","mali":"mali",
//    "niger":"niger","chad":"chad","central african republic":"central african republic","south sudan":"south sudan",
//    "eritrea":"eritrea","djibouti":"djibouti","somalia":"somalia","ethiopia":"ethiopia","kenya":"kenya","tanzania":"tanzania",
//    "uganda":"uganda","rwanda":"rwanda","burundi":"burundi","angola":"angola","zambia":"zambia","malawi":"malawi",
//    "mozambique":"mozambique","botswana":"botswana","namibia":"namibia","south africa":"south africa",
//    "lesotho":"lesotho","swaziland":"swaziland","madagascar":"madagascar","comoros":"comoros","seychelles":"seychelles","mauritius":"mauritius",
//    "cape verde":"cape verde","guinea":"guinea","guinea-bissau":"guinea-bissau","gambia":"gambia","senegal":"senegal",
//    "gambia":"gambia","senegal":"senegal","guinea":"guinea","guinea-bissau":"guinea-bissau","sierra leone":"sierra leone",
//    "liberia":"liberia","ivory coast":"ivory coast","burkina faso":"burkina faso","mali":"mali","niger":"niger",
//    "chad":"chad","central african republic":"central african republic","cameroon":"cameroon","equatorial guinea":"equatorial guinea",
//    "gabon":"gabon","congo":"congo","democratic republic of the congo":"democratic republic of the congo",
//    "angola":"angola","zambia":"zambia","malawi":"malawi","mozambique":"mozambique","botswana":"botswana",
//    "naples":"naples","turin":"turin","florence":"florence","milan":"milan","rome":"rome","venice":"venice",
//    "paris":"paris","lyon":"lyon","marseille":"marseille","nice":"nice","toulouse":"toulouse",
//    "berlin":"berlin","munich":"munich","hamburg":"hamburg","frankfurt":"frankfurt","cologne":"cologne",
//    "london":"london","manchester":"manchester","birmingham":"birmingham","leeds":"leeds","glasgow":"glasgow",
//    "edinburgh":"edinburgh","cardiff":"cardiff","belfast":"belfast","dublin":"dublin","cork":"cork","galway":"galway","limerick":"limerick","waterford":"waterford",
//    "lisbon":"lisbon","porto":"porto","coimbra":"coimbra","funchal":"funchal","braga":"braga","evora":"evora","guimaraes":"guimaraes",
//    "vienna":"vienna","graz":"graz","salzburg":"salzburg","innsbruck":"innsbruck","linz":"linz","klagenfurt":"klagenfurt",
//    "zurich":"zurich","geneva":"geneva","basel":"basel","lausanne":"lausanne","bern":"bern","winterthur":"winterthur",
//    "brussels":"brussels","antwerp":"antwerp","ghent":"ghent","charleroi":"charleroi","liege":"liege",
//    "stockholm":"stockholm","gothenburg":"gothenburg","malmo":"malmo","uppsala":"uppsala","vasteras":"vasteras",
//    "oslo":"oslo","bergen":"bergen","stavanger":"stavanger","trondheim":"trondheim","tromso":"tromso",
//    "copenhagen":"copenhagen","aarhus":"aarhus","odense":"odense","aalborg":"aalborg","esbjerg":"esbjerg",
//    "helsinki":"helsinki","tampere":"tampere","turku":"turku","oulu":"oulu","vantaa":"vantaa",
//    "warsaw":"warsaw","krakow":"krakow","lodz":"lodz","wroclaw":"wroclaw","poznan":"poznan",
//    "budapest":"budapest","debrecen":"debrecen","szeged":"szeged","miskolc":"miskolc","gyor":"gyor",
//    "prague":"prague","brno":"brno","ostrava":"ostrava","plzen":"plzen","liberec":"liberec",
//    "bucharest":"bucharest","cluj-napoca":"cluj-napoca","timisoara":"timisoara","iasi":"iasi","constanta":"constanta",
//    "athens":"athens","thessaloniki":"thessaloniki","patras":"patras","heraklion":"heraklion","larissa":"larissa",
//    "kyiv":"kyiv","kharkiv":"kharkiv","odessa":"odessa","dnipro":"dnipro","donetsk":"donetsk",
//    "minsk":"minsk","brest":"brest","grodno":"grodno","vitebsk":"vitebsk","mogilev":"mogilev",
//    "baku":"baku","ganja":"ganja","sumqayit":"sumqayit","mingechevir":"mingechevir","lankaran":"lankaran",
//    "tbilisi":"tbilisi","batumi":"batumi","kutaisi":"kutaisi","rustavi":"rustavi","zugdidi":"zugdidi",
//    "yerevan":"yerevan","gyumri":"gyumri","vanadzor":"vanadzor","ejmiatsin":"ejmiatsin","hrazdan":"hrazdan",
//    "tashkent":"tashkent","samarkand":"samarkand","bukhara":"bukhara","nukus":"nukus","fergana":"fergana",
//    "marocco":"marocco","algeria":"algeria","tunisia":"tunisia","libya":"libya","egypt":"egypt",
//    "iraq":"iraq","iran":"iran","syria":"syria","lebanon":"lebanon","jordan":"jordan",
//    "saudi arabia":"saudi arabia","qatar":"qatar","kuwait":"kuwait","oman":"oman","yemen":"yemen",
//    "north korea":"north korea","south korea":"south korea","japan":"japan","china":"china","mongolia":"mongolia",
//    "thailand":"thailand","singapore":"singapore","malaysia":"malaysia","indonesia":"indonesia","philippines":"philippines",
//    "australia":"australia","new zealand":"new zealand","ethiopia":"ethiopia","tanzania":"tanzania","uganda":"uganda","rwanda":"rwanda",
//    "north africa":"north africa","west africa":"west africa","east africa":"east africa","central africa":"central africa","southern africa":"southern africa",
//    "europe":"europe","asia":"asia","america":"america","oceania":"oceania","americas":"americas","africa":"africa","world":"world",
//    ""
// };
const cities = {
  'Aalborg': 'Aalborg',
  'Aarhus': 'Aarhus',
  'Abu Dhabi': 'Abu Dhabi',
  'Abuja': 'Abuja',
  'Abéché': 'Abéché',
  'Accra': 'Accra',
  'Aconibe': 'Aconibe',
  'Adana': 'Adana',
  'Addis Ababa': 'Addis Ababa',
  'Addu City': 'Addu City',
  'Adelaide': 'Adelaide',
  'Aden': 'Aden',
  'Afega': 'Afega',
  'Afghanistan': 'Afghanistan',
  'Agadez': 'Agadez',
  'Agadir': 'Agadir',
  'Airai': 'Airai',
  'Aiwo': 'Aiwo',
  'Ajman': 'Ajman',
  'Aktobe': 'Aktobe',
  'Akureyri': 'Akureyri',
  'Al Ahmadi': 'Al Ahmadi',
  'Al Ain': 'Al Ain',
  'Al Khor': 'Al Khor',
  'Al Rayyan': 'Al Rayyan',
  'Al Wakrah': 'Al Wakrah',
  'Alajuela': 'Alajuela',
  'Albania': 'Albania',
  'Aleppo': 'Aleppo',
  'Alexandria': 'Alexandria',
  'Algeria': 'Algeria',
  'Algiers': 'Algiers',
  'Ali Sabieh': 'Ali Sabieh',
  'All Saints': 'All Saints',
  'Almaty': 'Almaty',
  'Amman': 'Amman',
  'Amsterdam': 'Amsterdam',
  'Anabar': 'Anabar',
  'Andijan': 'Andijan',
  'Andorra': 'Andorra',
  'Andorra la Vella': 'Andorra la Vella',
  'Anetan': 'Anetan',
  'Angola': 'Angola',
  'Anibare': 'Anibare',
  'Ankara': 'Ankara',
  'Anna Regina': 'Anna Regina',
  'Annaba': 'Annaba',
  'Anse Boileau': 'Anse Boileau',
  'Antananarivo': 'Antananarivo',
  'Antigua and Barbuda': 'Antigua and Barbuda',
  'Antofagasta': 'Antofagasta',
  'Antsirabe': 'Antsirabe',
  'Antwerp': 'Antwerp',
  'Apia': 'Apia',
  'Aqaba': 'Aqaba',
  'Arawa': 'Arawa',
  'Arequipa': 'Arequipa',
  'Argentina': 'Argentina',
  'Arima': 'Arima',
  'Armenia': 'Armenia',
  'Arusha': 'Arusha',
  'Asau': 'Asau',
  'Ashaiman': 'Ashaiman',
  'Ashgabat': 'Ashgabat',
  'Asmara': 'Asmara',
  'Assab': 'Assab',
  'Assomada': 'Assomada',
  'Astana': 'Astana',
  'Asunción': 'Asunción',
  'Atakpamé': 'Atakpamé',
  'Athens': 'Athens',
  'Atkinson': 'Atkinson',
  'Auckland': 'Auckland',
  'Auki': 'Auki',
  'Australia': 'Australia',
  'Austria': 'Austria',
  'Aweil': 'Aweil',
  'Azerbaijan': 'Azerbaijan',
  'Añisoc': 'Añisoc',
  'Ba': 'Ba',
  'Bafatá': 'Bafatá',
  'Baghdad': 'Baghdad',
  'Bago': 'Bago',
  'Bahamas': 'Bahamas',
  'Bahrain': 'Bahrain',
  'Bairiki': 'Bairiki',
  'Bakau': 'Bakau',
  'Baku': 'Baku',
  'Balkanabat': 'Balkanabat',
  'Bamako': 'Bamako',
  'Bamenda': 'Bamenda',
  'Bandar Seri Begawan': 'Bandar Seri Begawan',
  'Bandung': 'Bandung',
  'Banfora': 'Banfora',
  'Bangalore': 'Bangalore',
  'Bangar': 'Bangar',
  'Bangkok': 'Bangkok',
  'Bangladesh': 'Bangladesh',
  'Bangui': 'Bangui',
  'Banja Luka': 'Banja Luka',
  'Banjul': 'Banjul',
  'Banská Bystrica': 'Banská Bystrica',
  'Bar': 'Bar',
  'Barbados': 'Barbados',
  'Barcelona': 'Barcelona',
  'Barquisimeto': 'Barquisimeto',
  'Barranquilla': 'Barranquilla',
  'Barrouallie': 'Barrouallie',
  'Bartica': 'Bartica',
  'Basel': 'Basel',
  'Basra': 'Basra',
  'Basseterre': 'Basseterre',
  'Bata': 'Bata',
  'Bathsheba': 'Bathsheba',
  'Battambang': 'Battambang',
  'Batumi': 'Batumi',
  'Baucau': 'Baucau',
  'Beau Bassin-Rose Hill': 'Beau Bassin-Rose Hill',
  'Beau Vallon': 'Beau Vallon',
  'Beijing': 'Beijing',
  'Beira': 'Beira',
  'Beirut': 'Beirut',
  'Bel Ombre': 'Bel Ombre',
  'Belarus': 'Belarus',
  'Belgium': 'Belgium',
  'Belgrade': 'Belgrade',
  'Belize': 'Belize',
  'Belize City': 'Belize City',
  'Belmopan': 'Belmopan',
  'Bender': 'Bender',
  'Benghazi': 'Benghazi',
  'Benguela': 'Benguela',
  'Benin': 'Benin',
  'Benin City': 'Benin City',
  'Bensonville': 'Bensonville',
  'Berbera': 'Berbera',
  'Berberati': 'Berberati',
  'Berekua': 'Berekua',
  'Bergen': 'Bergen',
  'Berlin': 'Berlin',
  'Bern': 'Bern',
  'Betio': 'Betio',
  'Bharatpur': 'Bharatpur',
  'Bhutan': 'Bhutan',
  'Bijeljina': 'Bijeljina',
  'Bijelo Polje': 'Bijelo Polje',
  'Bikenibeu': 'Bikenibeu',
  'Bimbo': 'Bimbo',
  'Biratnagar': 'Biratnagar',
  'Birkirkara': 'Birkirkara',
  'Birmingham': 'Birmingham',
  'Bishkek': 'Bishkek',
  'Bissau': 'Bissau',
  'Bissorã': 'Bissorã',
  'Bisée': 'Bisée',
  'Bitola': 'Bitola',
  'Blantyre': 'Blantyre',
  'Blida': 'Blida',
  'Bo': 'Bo',
  'Bobo-Dioulasso': 'Bobo-Dioulasso',
  'Bogotá': 'Bogotá',
  'Bohicon': 'Bohicon',
  'Bolama': 'Bolama',
  'Bolands': 'Bolands',
  'Bolivia': 'Bolivia',
  'Borgo Maggiore': 'Borgo Maggiore',
  'Bosasso': 'Bosasso',
  'Bosnia and Herzegovina': 'Bosnia and Herzegovina',
  'Botswana': 'Botswana',
  'Braga': 'Braga',
  'Brasília': 'Brasília',
  'Bratislava': 'Bratislava',
  'Brazil': 'Brazil',
  'Brazzaville': 'Brazzaville',
  'Bridgetown': 'Bridgetown',
  'Brikama': 'Brikama',
  'Brisbane': 'Brisbane',
  'Brno': 'Brno',
  'Brunei': 'Brunei',
  'Brussels': 'Brussels',
  'Buala': 'Buala',
  'Bucharest': 'Bucharest',
  'Budapest': 'Budapest',
  'Buenos Aires': 'Buenos Aires',
  'Bujumbura': 'Bujumbura',
  'Bukhara': 'Bukhara',
  'Bulawayo': 'Bulawayo',
  'Bulgaria': 'Bulgaria',
  'Burgas': 'Burgas',
  'Burkina Faso': 'Burkina Faso',
  'Bursa': 'Bursa',
  'Burundi': 'Burundi',
  'Busan': 'Busan',
  'Butare': 'Butare',
  'Bălți': 'Bălți',
  'Cairo': 'Cairo',
  'Calgary': 'Calgary',
  'Cali': 'Cali',
  'Calliaqua': 'Calliaqua',
  'Caloocan': 'Caloocan',
  'Camagüey': 'Camagüey',
  'Cambodia': 'Cambodia',
  'Cameroon': 'Cameroon',
  'Canada': 'Canada',
  'Cap-Haïtien': 'Cap-Haïtien',
  'Cape Town': 'Cape Town',
  'Cape Verde': 'Cape Verde',
  'Caracas': 'Caracas',
  'Cartagena': 'Cartagena',
  'Cartago': 'Cartago',
  'Casablanca': 'Casablanca',
  'Cascade': 'Cascade',
  'Castries': 'Castries',
  'Cayon': 'Cayon',
  'Cebu City': 'Cebu City',
  'Celje': 'Celje',
  'Central African Republic': 'Central African Republic',
  'Chad': 'Chad',
  'Chaguanas': 'Chaguanas',
  'Charleroi': 'Charleroi',
  'Charlestown': 'Charlestown',
  'Chateaubelair': 'Chateaubelair',
  'Chengdu': 'Chengdu',
  'Chennai': 'Chennai',
  'Chiang Mai': 'Chiang Mai',
  'Chicago': 'Chicago',
  'Chiclayo': 'Chiclayo',
  'Chile': 'Chile',
  'China': 'China',
  'Chinandega': 'Chinandega',
  'Chingola': 'Chingola',
  'Chittagong': 'Chittagong',
  'Chitungwiza': 'Chitungwiza',
  'Chișinău': 'Chișinău',
  'Choibalsan': 'Choibalsan',
  'Choloma': 'Choloma',
  'Chongjin': 'Chongjin',
  'Christchurch': 'Christchurch',
  'Ciudad del Este': 'Ciudad del Este',
  'Ciudad Guayana': 'Ciudad Guayana',
  'Cluj-Napoca': 'Cluj-Napoca',
  'Cobán': 'Cobán',
  'Cochabamba': 'Cochabamba',
  'Coimbra': 'Coimbra',
  'Cologne': 'Cologne',
  'Colombia': 'Colombia',
  'Colombo': 'Colombo',
  'Colonia': 'Colonia',
  'Colón': 'Colón',
  'Comoros': 'Comoros',
  'Conakry': 'Conakry',
  'Concepción': 'Concepción',
  'Congo': 'Congo',
  'Constantine': 'Constantine',
  'Constanța': 'Constanța',
  'Cooper\'s Town': 'Cooper\'s Town',
  'Copenhagen': 'Copenhagen',
  'Cork': 'Cork',
  'Costa Rica': 'Costa Rica',
  'Cotonou': 'Cotonou',
  'Croatia': 'Croatia',
  'Cuba': 'Cuba',
  'Cuenca': 'Cuenca',
  'Curepipe': 'Curepipe',
  'Cyprus': 'Cyprus',
  'Czech Republic': 'Czech Republic',
  'Córdoba': 'Córdoba',
  'Cần Thơ': 'Cần Thơ',
  'Da Nang': 'Da Nang',
  'Daegu': 'Daegu',
  'Daejeon': 'Daejeon',
  'Dakar': 'Dakar',
  'Damascus': 'Damascus',
  'Dammam': 'Dammam',
  'Dangriga': 'Dangriga',
  'Dar es Salaam': 'Dar es Salaam',
  'Darkhan': 'Darkhan',
  'Daugavpils': 'Daugavpils',
  'Davao City': 'Davao City',
  'David': 'David',
  'Daşoguz': 'Daşoguz',
  'Debrecen': 'Debrecen',
  'Democratic Republic of the Congo': 'Democratic Republic of the Congo',
  'Denmark': 'Denmark',
  'Dhaka': 'Dhaka',
  'Differdange': 'Differdange',
  'Dikhil': 'Dikhil',
  'Dili': 'Dili',
  'Dire Dawa': 'Dire Dawa',
  'Djibouti': 'Djibouti',
  'Djibouti City': 'Djibouti City',
  'Djougou': 'Djougou',
  'Dnipro': 'Dnipro',
  'Dodoma': 'Dodoma',
  'Doha': 'Doha',
  'Dolisie': 'Dolisie',
  'Domagnano': 'Domagnano',
  'Dominica': 'Dominica',
  'Dominican Republic': 'Dominican Republic',
  'Domoni': 'Domoni',
  'Donetsk': 'Donetsk',
  'Douala': 'Douala',
  'Dubai': 'Dubai',
  'Dublin': 'Dublin',
  'Dudelange': 'Dudelange',
  'Durban': 'Durban',
  'Durrës': 'Durrës',
  'Dushanbe': 'Dushanbe',
  'Ebebiyín': 'Ebebiyín',
  'Ebeye': 'Ebeye',
  'Ecuador': 'Ecuador',
  'Egypt': 'Egypt',
  'Eindhoven': 'Eindhoven',
  'Eita': 'Eita',
  'El Progreso': 'El Progreso',
  'El Salvador': 'El Salvador',
  'Elbasan': 'Elbasan',
  'Eldoret': 'Eldoret',
  'Encamp': 'Encamp',
  'Equatorial Guinea': 'Equatorial Guinea',
  'Erbil': 'Erbil',
  'Erdenet': 'Erdenet',
  'Eritrea': 'Eritrea',
  'Esbjerg': 'Esbjerg',
  'Escaldes-Engordany': 'Escaldes-Engordany',
  'Esch-sur-Alzette': 'Esch-sur-Alzette',
  'Eschen': 'Eschen',
  'Escuintla': 'Escuintla',
  'Espoo': 'Espoo',
  'Estonia': 'Estonia',
  'Eswatini': 'Eswatini',
  'Ethiopia': 'Ethiopia',
  'Ettadhamen': 'Ettadhamen',
  'Ettelbruck': 'Ettelbruck',
  'Faisalabad': 'Faisalabad',
  'Faleolo': 'Faleolo',
  'Famagusta': 'Famagusta',
  'Farafenni': 'Farafenni',
  'Fernando de la Mora': 'Fernando de la Mora',
  'Fianarantsoa': 'Fianarantsoa',
  'Fiji': 'Fiji',
  'Finland': 'Finland',
  'Fiorentino': 'Fiorentino',
  'Fomboni': 'Fomboni',
  'Fontvieille': 'Fontvieille',
  'Fortaleza': 'Fortaleza',
  'France': 'France',
  'Franceville': 'Franceville',
  'Francistown': 'Francistown',
  'Frankfurt': 'Frankfurt',
  'Freeport': 'Freeport',
  'Freetown': 'Freetown',
  'Funafuti': 'Funafuti',
  'Funchal': 'Funchal',
  'Fuvahmulah': 'Fuvahmulah',
  'Fès': 'Fès',
  'Gabon': 'Gabon',
  'Gaborone': 'Gaborone',
  'Gabú': 'Gabú',
  'Galle': 'Galle',
  'Galway': 'Galway',
  'Gambia': 'Gambia',
  'Ganja': 'Ganja',
  'Garoua': 'Garoua',
  'Gbarnga': 'Gbarnga',
  'Geneva': 'Geneva',
  'George Town': 'George Town',
  'Georgetown': 'Georgetown',
  'Georgia': 'Georgia',
  'Germany': 'Germany',
  'Ghana': 'Ghana',
  'Ghent': 'Ghent',
  'Gingerland': 'Gingerland',
  'Gisenyi': 'Gisenyi',
  'Gitarama': 'Gitarama',
  'Gitega': 'Gitega',
  'Giza': 'Giza',
  'Gizo': 'Gizo',
  'Glasgow': 'Glasgow',
  'Gomel': 'Gomel',
  'Gonaïves': 'Gonaïves',
  'Gondar': 'Gondar',
  'Gothenburg': 'Gothenburg',
  'Gouyave': 'Gouyave',
  'Graz': 'Graz',
  'Greece': 'Greece',
  'Grenada': 'Grenada',
  'Grenville': 'Grenville',
  'Grodno': 'Grodno',
  'Guadalajara': 'Guadalajara',
  'Guangzhou': 'Guangzhou',
  'Guatemala': 'Guatemala',
  'Guatemala City': 'Guatemala City',
  'Guayaquil': 'Guayaquil',
  'Guinea': 'Guinea',
  'Guinea-Bissau': 'Guinea-Bissau',
  'Gulu': 'Gulu',
  'Guyana': 'Guyana',
  'Gweru': 'Gweru',
  'Gyumri': 'Gyumri',
  'Hafnarfjörður': 'Hafnarfjörður',
  'Haifa': 'Haifa',
  'Haiphong': 'Haiphong',
  'Haiti': 'Haiti',
  'Hama': 'Hama',
  'Hamad Town': 'Hamad Town',
  'Hamburg': 'Hamburg',
  'Hamhung': 'Hamhung',
  'Hamilton': 'Hamilton',
  'Hanoi': 'Hanoi',
  'Harare': 'Harare',
  'Hargeisa': 'Hargeisa',
  'Harper': 'Harper',
  'Hat Yai': 'Hat Yai',
  'Havana': 'Havana',
  'Haveluloto': 'Haveluloto',
  'Hawalli': 'Hawalli',
  'Hawassa': 'Hawassa',
  'Helsinki': 'Helsinki',
  'Heraklion': 'Heraklion',
  'Herat': 'Herat',
  'Herceg Novi': 'Herceg Novi',
  'Heredia': 'Heredia',
  'Hlotse': 'Hlotse',
  'Ho Chi Minh City': 'Ho Chi Minh City',
  'Hodeidah': 'Hodeidah',
  'Holetown': 'Holetown',
  'Holguín': 'Holguín',
  'Homs': 'Homs',
  'Honduras': 'Honduras',
  'Honiara': 'Honiara',
  'Houston': 'Houston',
  'Hrazdan': 'Hrazdan',
  'Huambo': 'Huambo',
  'Hungary': 'Hungary',
  'Hyderabad': 'Hyderabad',
  'Iași': 'Iași',
  'Ibadan': 'Ibadan',
  'Iceland': 'Iceland',
  'Impfondo': 'Impfondo',
  'Incheon': 'Incheon',
  'India': 'India',
  'Indonesia': 'Indonesia',
  'Innsbruck': 'Innsbruck',
  'Ipoh': 'Ipoh',
  'Iran': 'Iran',
  'Iraq': 'Iraq',
  'Irbid': 'Irbid',
  'Ireland': 'Ireland',
  'Isa Town': 'Isa Town',
  'Isangel': 'Isangel',
  'Isfahan': 'Isfahan',
  'Islamabad': 'Islamabad',
  'Israel': 'Israel',
  'Istanbul': 'Istanbul',
  'Istaravshan': 'Istaravshan',
  'Italy': 'Italy',
  'Izmir': 'Izmir',
  'Jabor': 'Jabor',
  'Jaffna': 'Jaffna',
  'Jakarta': 'Jakarta',
  'Jalal-Abad': 'Jalal-Abad',
  'Jalalabad': 'Jalalabad',
  'Jamaica': 'Jamaica',
  'Japan': 'Japan',
  'Jeddah': 'Jeddah',
  'Jelgava': 'Jelgava',
  'Jerusalem': 'Jerusalem',
  'Jinja': 'Jinja',
  'Johannesburg': 'Johannesburg',
  'Jordan': 'Jordan',
  'Juba': 'Juba',
  'Jūrmala': 'Jūrmala',
  'Kabul': 'Kabul',
  'Kabwe': 'Kabwe',
  'Kaga-Bandoro': 'Kaga-Bandoro',
  'Kairouan': 'Kairouan',
  'Kakata': 'Kakata',
  'Kampala': 'Kampala',
  'Kampong Cham': 'Kampong Cham',
  'Kananga': 'Kananga',
  'Kandahar': 'Kandahar',
  'Kandy': 'Kandy',
  'Kankan': 'Kankan',
  'Kano': 'Kano',
  'Kaohsiung': 'Kaohsiung',
  'Kaolack': 'Kaolack',
  'Kara': 'Kara',
  'Karachi': 'Karachi',
  'Karaganda': 'Karaganda',
  'Karaj': 'Karaj',
  'Karakol': 'Karakol',
  'Kassala': 'Kassala',
  'Kasungu': 'Kasungu',
  'Kathmandu': 'Kathmandu',
  'Kaunas': 'Kaunas',
  'Kazakhstan': 'Kazakhstan',
  'Kazan': 'Kazan',
  'Kaédi': 'Kaédi',
  'Kelo': 'Kelo',
  'Kenema': 'Kenema',
  'Kenya': 'Kenya',
  'Keren': 'Keren',
  'Kharkiv': 'Kharkiv',
  'Khartoum': 'Khartoum',
  'Khujand': 'Khujand',
  'Khulna': 'Khulna',
  'Kigali': 'Kigali',
  'Kindia': 'Kindia',
  'Kingston': 'Kingston',
  'Kingstown': 'Kingstown',
  'Kinshasa': 'Kinshasa',
  'Kirakira': 'Kirakira',
  'Kiribati': 'Kiribati',
  'Kirkuk': 'Kirkuk',
  'Kisangani': 'Kisangani',
  'Kismayo': 'Kismayo',
  'Kisumu': 'Kisumu',
  'Kitwe': 'Kitwe',
  'Klaipėda': 'Klaipėda',
  'Kohtla-Järve': 'Kohtla-Järve',
  'Koidu': 'Koidu',
  'Koror': 'Koror',
  'Kosti': 'Kosti',
  'Koudougou': 'Koudougou',
  'Koutiala': 'Koutiala',
  'Košice': 'Košice',
  'Kpalimé': 'Kpalimé',
  'Kragujevac': 'Kragujevac',
  'Kraków': 'Kraków',
  'Kranj': 'Kranj',
  'Kuala Belait': 'Kuala Belait',
  'Kuala Lumpur': 'Kuala Lumpur',
  'Kulhudhuffushi': 'Kulhudhuffushi',
  'Kulob': 'Kulob',
  'Kumanovo': 'Kumanovo',
  'Kumasi': 'Kumasi',
  'Kutaisi': 'Kutaisi',
  'Kuwait': 'Kuwait',
  'Kuwait City': 'Kuwait City',
  'Kyiv': 'Kyiv',
  'Kyrgyzstan': 'Kyrgyzstan',
  'Kópavogur': 'Kópavogur',
  'La Ceiba': 'La Ceiba',
  'La Condamine': 'La Condamine',
  'La Massana': 'La Massana',
  'La Paz': 'La Paz',
  'La Romana': 'La Romana',
  'Labasa': 'Labasa',
  'Labé': 'Labé',
  'Lae': 'Lae',
  'Lagos': 'Lagos',
  'Lahore': 'Lahore',
  'Lalitpur': 'Lalitpur',
  'Lankaran': 'Lankaran',
  'Laos': 'Laos',
  'Larissa': 'Larissa',
  'Larnaca': 'Larnaca',
  'Las Piedras': 'Las Piedras',
  'Latakia': 'Latakia',
  'Latvia': 'Latvia',
  'Lausanne': 'Lausanne',
  'Lautoka': 'Lautoka',
  'Lebanon': 'Lebanon',
  'Leeds': 'Leeds',
  'Lelu': 'Lelu',
  'Lelydorp': 'Lelydorp',
  'Les Cayes': 'Les Cayes',
  'Lesotho': 'Lesotho',
  'León': 'León',
  'Liberec': 'Liberec',
  'Liberia': 'Liberia',
  'Liberta': 'Liberta',
  'Libreville': 'Libreville',
  'Libya': 'Libya',
  'Liechtenstein': 'Liechtenstein',
  'Liepāja': 'Liepāja',
  'Lilongwe': 'Lilongwe',
  'Lima': 'Lima',
  'Limassol': 'Limassol',
  'Limerick': 'Limerick',
  'Linden': 'Linden',
  'Linz': 'Linz',
  'Lira': 'Lira',
  'Lisbon': 'Lisbon',
  'Lithuania': 'Lithuania',
  'Liège': 'Liège',
  'Ljubljana': 'Ljubljana',
  'Lobamba': 'Lobamba',
  'Lobito': 'Lobito',
  'Lomé': 'Lomé',
  'London': 'London',
  'Los Angeles': 'Los Angeles',
  'Lospalos': 'Lospalos',
  'Luanda': 'Luanda',
  'Luang Prabang': 'Luang Prabang',
  'Lubumbashi': 'Lubumbashi',
  'Luganville': 'Luganville',
  'Luque': 'Luque',
  'Lusaka': 'Lusaka',
  'Luxembourg': 'Luxembourg',
  'Luxembourg City': 'Luxembourg City',
  'Lyon': 'Lyon',
  'Machala': 'Machala',
  'Madagascar': 'Madagascar',
  'Madang': 'Madang',
  'Madinat ash Shamal': 'Madinat ash Shamal',
  'Madrid': 'Madrid',
  'Mafeteng': 'Mafeteng',
  'Mahajanga': 'Mahajanga',
  'Majuro': 'Majuro',
  'Makeni': 'Makeni',
  'Malabo': 'Malabo',
  'Malakal': 'Malakal',
  'Malawi': 'Malawi',
  'Malaysia': 'Malaysia',
  'Maldives': 'Maldives',
  'Mali': 'Mali',
  'Maliana': 'Maliana',
  'Malmö': 'Malmö',
  'Malta': 'Malta',
  'Malé': 'Malé',
  'Managua': 'Managua',
  'Manama': 'Manama',
  'Manchester': 'Manchester',
  'Mandalay': 'Mandalay',
  'Mandeville': 'Mandeville',
  'Manila': 'Manila',
  'Manzini': 'Manzini',
  'Maputo': 'Maputo',
  'Maracaibo': 'Maracaibo',
  'Maradi': 'Maradi',
  'Maribor': 'Maribor',
  'Marigot': 'Marigot',
  'Maroua': 'Maroua',
  'Marrakech': 'Marrakech',
  'Marseille': 'Marseille',
  'Marsh Harbour': 'Marsh Harbour',
  'Marshall Islands': 'Marshall Islands',
  'Mary': 'Mary',
  'Masaya': 'Masaya',
  'Maseru': 'Maseru',
  'Mashhad': 'Mashhad',
  'Massawa': 'Massawa',
  'Matagalpa': 'Matagalpa',
  'Maun': 'Maun',
  'Mauren': 'Mauren',
  'Mauritania': 'Mauritania',
  'Mauritius': 'Mauritius',
  'Mawlamyine': 'Mawlamyine',
  'Mazar-i-Sharif': 'Mazar-i-Sharif',
  'Mazatenango': 'Mazatenango',
  'Mbabane': 'Mbabane',
  'Mbarara': 'Mbarara',
  'Mbaïki': 'Mbaïki',
  'Mbeya': 'Mbeya',
  'Mbuji-Mayi': 'Mbuji-Mayi',
  'Mecca': 'Mecca',
  'Medan': 'Medan',
  'Medellín': 'Medellín',
  'Medina': 'Medina',
  'Mejicanos': 'Mejicanos',
  'Mekelle': 'Mekelle',
  'Melbourne': 'Melbourne',
  'Mendefera': 'Mendefera',
  'Mendoza': 'Mendoza',
  'Mexico': 'Mexico',
  'Mexico City': 'Mexico City',
  'Meyungs': 'Meyungs',
  'Micoud': 'Micoud',
  'Micronesia': 'Micronesia',
  'Milan': 'Milan',
  'Mili': 'Mili',
  'Mindelo': 'Mindelo',
  'Mingachevir': 'Mingachevir',
  'Minsk': 'Minsk',
  'Miskolc': 'Miskolc',
  'Misrata': 'Misrata',
  'Mitsamiouli': 'Mitsamiouli',
  'Moanda': 'Moanda',
  'Moengo': 'Moengo',
  'Mogadishu': 'Mogadishu',
  'Mogilev': 'Mogilev',
  'Mohale\'s Hoek': 'Mohale\'s Hoek',
  'Moldova': 'Moldova',
  'Molepolole': 'Molepolole',
  'Mombasa': 'Mombasa',
  'Monaco': 'Monaco',
  'Moneghetti': 'Moneghetti',
  'Mongolia': 'Mongolia',
  'Monrovia': 'Monrovia',
  'Monte Carlo': 'Monte Carlo',
  'Montego Bay': 'Montego Bay',
  'Montenegro': 'Montenegro',
  'Monterrey': 'Monterrey',
  'Montevideo': 'Montevideo',
  'Montreal': 'Montreal',
  'Mopti': 'Mopti',
  'Morocco': 'Morocco',
  'Moroni': 'Moroni',
  'Moscow': 'Moscow',
  'Mosta': 'Mosta',
  'Mosul': 'Mosul',
  'Moundou': 'Moundou',
  'Mount Hagen': 'Mount Hagen',
  'Mozambique': 'Mozambique',
  'Muharraq': 'Muharraq',
  'Mukalla': 'Mukalla',
  'Mulifanua': 'Mulifanua',
  'Mumbai': 'Mumbai',
  'Munich': 'Munich',
  'Muscat': 'Muscat',
  'Mutare': 'Mutare',
  'Mutsamudu': 'Mutsamudu',
  'Muyinga': 'Muyinga',
  'Mwanza': 'Mwanza',
  'Myanmar': 'Myanmar',
  'Mzuzu': 'Mzuzu',
  'Mörön': 'Mörön',
  'N\'Djamena': 'N\'Djamena',
  'Nabatieh': 'Nabatieh',
  'Nadi': 'Nadi',
  'Nagoya': 'Nagoya',
  'Nairobi': 'Nairobi',
  'Nakhon Ratchasima': 'Nakhon Ratchasima',
  'Nakuru': 'Nakuru',
  'Namangan': 'Namangan',
  'Namibe': 'Namibe',
  'Namibia': 'Namibia',
  'Nampo': 'Nampo',
  'Nampula': 'Nampula',
  'Naples': 'Naples',
  'Narva': 'Narva',
  'Nassau': 'Nassau',
  'Nauru': 'Nauru',
  'Naypyidaw': 'Naypyidaw',
  'Ndola': 'Ndola',
  'Negombo': 'Negombo',
  'Neiafu': 'Neiafu',
  'Nepal': 'Nepal',
  'Netherlands': 'Netherlands',
  'New Amsterdam': 'New Amsterdam',
  'New Delhi': 'New Delhi',
  'New York': 'New York',
  'New Zealand': 'New Zealand',
  'Ngchemiangel': 'Ngchemiangel',
  'Ngerulmud': 'Ngerulmud',
  'Ngozi': 'Ngozi',
  'Nhlangano': 'Nhlangano',
  'Niamey': 'Niamey',
  'Nicaragua': 'Nicaragua',
  'Nice': 'Nice',
  'Nicosia': 'Nicosia',
  'Nieuw Amsterdam': 'Nieuw Amsterdam',
  'Nieuw Nickerie': 'Nieuw Nickerie',
  'Niger': 'Niger',
  'Nigeria': 'Nigeria',
  'Nikšić': 'Nikšić',
  'Nizwa': 'Nizwa',
  'Niš': 'Niš',
  'Nkayi': 'Nkayi',
  'Nonthaburi': 'Nonthaburi',
  'Norsup': 'Norsup',
  'North Korea': 'North Korea',
  'North Macedonia': 'North Macedonia',
  'Norway': 'Norway',
  'Nouadhibou': 'Nouadhibou',
  'Nouakchott': 'Nouakchott',
  'Novi Sad': 'Novi Sad',
  'Novosibirsk': 'Novosibirsk',
  'Nuku\'alofa': 'Nuku\'alofa',
  'Nzérékoré': 'Nzérékoré',
  'Néma': 'Néma',
  'Obock': 'Obock',
  'Odense': 'Odense',
  'Odessa': 'Odessa',
  'Ohrid': 'Ohrid',
  'Oistins': 'Oistins',
  'Oman': 'Oman',
  'Omdurman': 'Omdurman',
  'Oran': 'Oran',
  'Orange Walk': 'Orange Walk',
  'Oruro': 'Oruro',
  'Osaka': 'Osaka',
  'Osh': 'Osh',
  'Oshakati': 'Oshakati',
  'Osijek': 'Osijek',
  'Oslo': 'Oslo',
  'Ostrava': 'Ostrava',
  'Ottawa': 'Ottawa',
  'Ouagadougou': 'Ouagadougou',
  'Ouahigouya': 'Ouahigouya',
  'Oulu': 'Oulu',
  'Oyem': 'Oyem',
  'Pakistan': 'Pakistan',
  'Pakse': 'Pakse',
  'Palau': 'Palau',
  'Palermo': 'Palermo',
  'Palikir': 'Palikir',
  'Panama': 'Panama',
  'Panama City': 'Panama City',
  'Panevėžys': 'Panevėžys',
  'Pangai': 'Pangai',
  'Paphos': 'Paphos',
  'Papua New Guinea': 'Papua New Guinea',
  'Paraguay': 'Paraguay',
  'Parakou': 'Parakou',
  'Paramaribo': 'Paramaribo',
  'Paris': 'Paris',
  'Patras': 'Patras',
  'Paysandú': 'Paysandú',
  'Pedra Badejo': 'Pedra Badejo',
  'Perth': 'Perth',
  'Peru': 'Peru',
  'Petah Tikva': 'Petah Tikva',
  'Petaling Jaya': 'Petaling Jaya',
  'Philippines': 'Philippines',
  'Phnom Penh': 'Phnom Penh',
  'Phoenix': 'Phoenix',
  'Phuntsholing': 'Phuntsholing',
  'Piura': 'Piura',
  'Plovdiv': 'Plovdiv',
  'Plzeň': 'Plzeň',
  'Podgorica': 'Podgorica',
  'Point Fortin': 'Point Fortin',
  'Pointe-Noire': 'Pointe-Noire',
  'Pokhara': 'Pokhara',
  'Poland': 'Poland',
  'Port Elizabeth': 'Port Elizabeth',
  'Port Louis': 'Port Louis',
  'Port Moresby': 'Port Moresby',
  'Port of Spain': 'Port of Spain',
  'Port Olry': 'Port Olry',
  'Port Said': 'Port Said',
  'Port Sudan': 'Port Sudan',
  'Port Vila': 'Port Vila',
  'Port-au-Prince': 'Port-au-Prince',
  'Port-Gentil': 'Port-Gentil',
  'Portmore': 'Portmore',
  'Porto': 'Porto',
  'Porto-Novo': 'Porto-Novo',
  'Portsmouth': 'Portsmouth',
  'Portugal': 'Portugal',
  'Potter\'s Village': 'Potter\'s Village',
  'Poznań': 'Poznań',
  'Prague': 'Prague',
  'Praia': 'Praia',
  'Pretoria': 'Pretoria',
  'Prešov': 'Prešov',
  'Puebla': 'Puebla',
  'Punakha': 'Punakha',
  'Pyongyang': 'Pyongyang',
  'Pärnu': 'Pärnu',
  'Pécs': 'Pécs',
  'Qatar': 'Qatar',
  'Qormi': 'Qormi',
  'Quatre Bornes': 'Quatre Bornes',
  'Quelimane': 'Quelimane',
  'Quetzaltenango': 'Quetzaltenango',
  'Quezon City': 'Quezon City',
  'Quito': 'Quito',
  'Qŭrghonteppa': 'Qŭrghonteppa',
  'Rabat': 'Rabat',
  'Rajshahi': 'Rajshahi',
  'Rawalpindi': 'Rawalpindi',
  'Reykjanesbær': 'Reykjanesbær',
  'Reykjavik': 'Reykjavik',
  'Riffa': 'Riffa',
  'Riga': 'Riga',
  'Rijeka': 'Rijeka',
  'Rio de Janeiro': 'Rio de Janeiro',
  'Rishon LeZion': 'Rishon LeZion',
  'Rivera': 'Rivera',
  'Riyadh': 'Riyadh',
  'Romania': 'Romania',
  'Rome': 'Rome',
  'Rosario': 'Rosario',
  'Roseau': 'Roseau',
  'Rosso': 'Rosso',
  'Rotterdam': 'Rotterdam',
  'Ruhengeri': 'Ruhengeri',
  'Rumonge': 'Rumonge',
  'Rundu': 'Rundu',
  'Russeifa': 'Russeifa',
  'Russia': 'Russia',
  'Rustavi': 'Rustavi',
  'Rwanda': 'Rwanda',
  'Rîbnița': 'Rîbnița',
  'Sabah Al Salem': 'Sabah Al Salem',
  'Saint George\'s': 'Saint George\'s',
  'Saint John\'s': 'Saint John\'s',
  'Saint Kitts and Nevis': 'Saint Kitts and Nevis',
  'Saint Lucia': 'Saint Lucia',
  'Saint Petersburg': 'Saint Petersburg',
  'Saint Vincent and the Grenadines': 'Saint Vincent and the Grenadines',
  'Saint-Louis': 'Saint-Louis',
  'Saint-Marc': 'Saint-Marc',
  'Salalah': 'Salalah',
  'Salmiya': 'Salmiya',
  'Salto': 'Salto',
  'Salvador': 'Salvador',
  'Salzburg': 'Salzburg',
  'Samarkand': 'Samarkand',
  'Samoa': 'Samoa',
  'San Fernando': 'San Fernando',
  'San Francisco de Macorís': 'San Francisco de Macorís',
  'San Ignacio': 'San Ignacio',
  'San José': 'San José',
  'San Lorenzo': 'San Lorenzo',
  'San Marino': 'San Marino',
  'San Marino City': 'San Marino City',
  'San Miguel': 'San Miguel',
  'San Miguelito': 'San Miguelito',
  'San Pedro de Macorís': 'San Pedro de Macorís',
  'San Pedro Sula': 'San Pedro Sula',
  'San Salvador': 'San Salvador',
  'Sanaa': 'Sanaa',
  'Sandy Point Town': 'Sandy Point Town',
  'Sant Julià de Lòria': 'Sant Julià de Lòria',
  'Santa Ana': 'Santa Ana',
  'Santa Clara': 'Santa Clara',
  'Santa Cruz': 'Santa Cruz',
  'Santa Maria': 'Santa Maria',
  'Santiago': 'Santiago',
  'Santiago de Cuba': 'Santiago de Cuba',
  'Santo Domingo': 'Santo Domingo',
  'Sapporo': 'Sapporo',
  'Sarajevo': 'Sarajevo',
  'Sarh': 'Sarh',
  'Saudi Arabia': 'Saudi Arabia',
  'Sauteurs': 'Sauteurs',
  'Savannakhet': 'Savannakhet',
  'Savave': 'Savave',
  'Schaan': 'Schaan',
  'Sekondi-Takoradi': 'Sekondi-Takoradi',
  'Semarang': 'Semarang',
  'Senegal': 'Senegal',
  'Seoul': 'Seoul',
  'Serbia': 'Serbia',
  'Serekunda': 'Serekunda',
  'Seria': 'Seria',
  'Serowe': 'Serowe',
  'Serravalle': 'Serravalle',
  'Seville': 'Seville',
  'Seychelles': 'Seychelles',
  'Sfax': 'Sfax',
  'Shah Alam': 'Shah Alam',
  'Shanghai': 'Shanghai',
  'Sharjah': 'Sharjah',
  'Shenzhen': 'Shenzhen',
  'Shkodër': 'Shkodër',
  'Shubra El Kheima': 'Shubra El Kheima',
  'Shymkent': 'Shymkent',
  'Sidon': 'Sidon',
  'Siem Reap': 'Siem Reap',
  'Sierra Leone': 'Sierra Leone',
  'Sihanoukville': 'Sihanoukville',
  'Sikasso': 'Sikasso',
  'Singapore': 'Singapore',
  'Siteki': 'Siteki',
  'Skopje': 'Skopje',
  'Slovakia': 'Slovakia',
  'Slovenia': 'Slovenia',
  'Sofia': 'Sofia',
  'Sohar': 'Sohar',
  'Sokodé': 'Sokodé',
  'Solomon Islands': 'Solomon Islands',
  'Somalia': 'Somalia',
  'Soufrière': 'Soufrière',
  'Sousse': 'Sousse',
  'South Africa': 'South Africa',
  'South Korea': 'South Korea',
  'South Sudan': 'South Sudan',
  'South Tarawa': 'South Tarawa',
  'Soyapango': 'Soyapango',
  'Spain': 'Spain',
  'Spanish Town': 'Spanish Town',
  'Speightstown': 'Speightstown',
  'Split': 'Split',
  'Sri Lanka': 'Sri Lanka',
  'Stara Zagora': 'Stara Zagora',
  'Stavanger': 'Stavanger',
  'Stockholm': 'Stockholm',
  'Suai': 'Suai',
  'Subotica': 'Subotica',
  'Sucre': 'Sucre',
  'Sudan': 'Sudan',
  'Sumqayit': 'Sumqayit',
  'Sur': 'Sur',
  'Surabaya': 'Surabaya',
  'Suriname': 'Suriname',
  'Suva': 'Suva',
  'Swakopmund': 'Swakopmund',
  'Sweden': 'Sweden',
  'Switzerland': 'Switzerland',
  'Sydney': 'Sydney',
  'Sylhet': 'Sylhet',
  'Syria': 'Syria',
  'Szeged': 'Szeged',
  'São Paulo': 'São Paulo',
  'Ségou': 'Ségou',
  'Tabriz': 'Tabriz',
  'Tadjourah': 'Tadjourah',
  'Tahoua': 'Tahoua',
  'Taichung': 'Taichung',
  'Tainan': 'Tainan',
  'Taipei': 'Taipei',
  'Taiwan': 'Taiwan',
  'Taiz': 'Taiz',
  'Tajikistan': 'Tajikistan',
  'Tallinn': 'Tallinn',
  'Tamale': 'Tamale',
  'Tampere': 'Tampere',
  'Tanrake': 'Tanrake',
  'Tanzania': 'Tanzania',
  'Taoyuan': 'Taoyuan',
  'Tarhuna': 'Tarhuna',
  'Tartu': 'Tartu',
  'Tashkent': 'Tashkent',
  'Tauranga': 'Tauranga',
  'Tbilisi': 'Tbilisi',
  'Tegucigalpa': 'Tegucigalpa',
  'Tehran': 'Tehran',
  'Tel Aviv': 'Tel Aviv',
  'Tete': 'Tete',
  'Tetovo': 'Tetovo',
  'Teyateyaneng': 'Teyateyaneng',
  'Thailand': 'Thailand',
  'The Hague': 'The Hague',
  'Thessaloniki': 'Thessaloniki',
  'Thimphu': 'Thimphu',
  'Thinadhoo': 'Thinadhoo',
  'Thiès': 'Thiès',
  'Tijuana': 'Tijuana',
  'Timișoara': 'Timișoara',
  'Timor-Leste': 'Timor-Leste',
  'Tirana': 'Tirana',
  'Tiraspol': 'Tiraspol',
  'Toamasina': 'Toamasina',
  'Tocumen': 'Tocumen',
  'Tofol': 'Tofol',
  'Toga': 'Toga',
  'Togo': 'Togo',
  'Tokmok': 'Tokmok',
  'Tokyo': 'Tokyo',
  'Tonga': 'Tonga',
  'Toronto': 'Toronto',
  'Touba': 'Touba',
  'Toulouse': 'Toulouse',
  'Triesen': 'Triesen',
  'Trinidad and Tobago': 'Trinidad and Tobago',
  'Tripoli': 'Tripoli',
  'Tromsø': 'Tromsø',
  'Trondheim': 'Trondheim',
  'Trujillo': 'Trujillo',
  'Tsirang': 'Tsirang',
  'Tucumán': 'Tucumán',
  'Tunis': 'Tunis',
  'Tunisia': 'Tunisia',
  'Turin': 'Turin',
  'Turkey': 'Turkey',
  'Turkmenistan': 'Turkmenistan',
  'Tutong': 'Tutong',
  'Tuvalu': 'Tuvalu',
  'Tuzla': 'Tuzla',
  'Tyre': 'Tyre',
  'Türkmenabat': 'Türkmenabat',
  'Uganda': 'Uganda',
  'Ukraine': 'Ukraine',
  'Ulaanbaatar': 'Ulaanbaatar',
  'United Arab Emirates': 'United Arab Emirates',
  'United Kingdom': 'United Kingdom',
  'United States': 'United States',
  'Uppsala': 'Uppsala',
  'Uruguay': 'Uruguay',
  'Utrecht': 'Utrecht',
  'Uzbekistan': 'Uzbekistan',
  'Vacoas-Phoenix': 'Vacoas-Phoenix',
  'Vaduz': 'Vaduz',
  'Vagharshapat': 'Vagharshapat',
  'Vaini': 'Vaini',
  'Valencia': 'Valencia',
  'Valletta': 'Valletta',
  'Valparaíso': 'Valparaíso',
  'Vanadzor': 'Vanadzor',
  'Vancouver': 'Vancouver',
  'Vang Vieng': 'Vang Vieng',
  'Vantaa': 'Vantaa',
  'Vanuatu': 'Vanuatu',
  'Varna': 'Varna',
  'Vatican City': 'Vatican City',
  'Velenje': 'Velenje',
  'Venezuela': 'Venezuela',
  'Victoria': 'Victoria',
  'Vienna': 'Vienna',
  'Vientiane': 'Vientiane',
  'Vietnam': 'Vietnam',
  'Vieux Fort': 'Vieux Fort',
  'Vilnius': 'Vilnius',
  'Vitebsk': 'Vitebsk',
  'Viña del Mar': 'Viña del Mar',
  'Vlorë': 'Vlorë',
  'Västerås': 'Västerås',
  'Walvis Bay': 'Walvis Bay',
  'Wangdue Phodrang': 'Wangdue Phodrang',
  'Warsaw': 'Warsaw',
  'Waterford': 'Waterford',
  'Wau': 'Wau',
  'Wellington': 'Wellington',
  'Weno': 'Weno',
  'West End': 'West End',
  'Windhoek': 'Windhoek',
  'Wonsan': 'Wonsan',
  'Wotje': 'Wotje',
  'Wrocław': 'Wrocław',
  'Yangon': 'Yangon',
  'Yaoundé': 'Yaoundé',
  'Yaren': 'Yaren',
  'Yei': 'Yei',
  'Yekaterinburg': 'Yekaterinburg',
  'Yemen': 'Yemen',
  'Yerevan': 'Yerevan',
  'Yokohama': 'Yokohama',
  'Zadar': 'Zadar',
  'Zagreb': 'Zagreb',
  'Zambia': 'Zambia',
  'Zaragoza': 'Zaragoza',
  'Zarqa': 'Zarqa',
  'Zawiya': 'Zawiya',
  'Zenica': 'Zenica',
  'Zimbabwe': 'Zimbabwe',
  'Zinder': 'Zinder',
  'Zomba': 'Zomba',
  'Zugdidi': 'Zugdidi',
  'Zurich': 'Zurich',
  'Łódź': 'Łódź',
  'Šiauliai': 'Šiauliai',
  'Żabbar': 'Żabbar',
  'Žilina': 'Žilina',
  'Attock': 'Attock',
'Bahawalnagar': 'Bahawalnagar',
'Bahawalpur': 'Bahawalpur',
'Bhakkar': 'Bhakkar',
'Burewala': 'Burewala',
'Chakwal': 'Chakwal',
'Chichawatni': 'Chichawatni',
'Chiniot': 'Chiniot',
'Dera Ghazi Khan': 'Dera Ghazi Khan',
'Faisalabad': 'Faisalabad',
'Gojra': 'Gojra',
'Gujranwala': 'Gujranwala',
'Gujrat': 'Gujrat',
'Hafizabad': 'Hafizabad',
'Islamabad': 'Islamabad',
'Jaranwala': 'Jaranwala',
'Jhang': 'Jhang',
'Jhelum': 'Jhelum',
'Kamalia': 'Kamalia',
'Kamoke': 'Kamoke',
'Kasur': 'Kasur',
'Khanewal': 'Khanewal',
'Khushab': 'Khushab',
'Kot Addu': 'Kot Addu',
'Lahore': 'Lahore',
'Layyah': 'Layyah',
'Lodhran': 'Lodhran',
'Mandi Bahauddin': 'Mandi Bahauddin',
'Mianwali': 'Mianwali',
'Multan': 'Multan',
'Muridke': 'Muridke',
'Muzaffargarh': 'Muzaffargarh',
'Nankana Sahib': 'Nankana Sahib',
'Narowal': 'Narowal',
'Okara': 'Okara',
'Pakpattan': 'Pakpattan',
'Pir Mahal': 'Pir Mahal',
'Rahim Yar Khan': 'Rahim Yar Khan',
'Rajana': 'Rajana',
'Rawalpindi': 'Rawalpindi',
'Sadiqabad': 'Sadiqabad',
'Sahiwal': 'Sahiwal',
'Samundri': 'Samundri',
'Sargodha': 'Sargodha',
'Shahkot': 'Shahkot',
'Sheikhupura': 'Sheikhupura',
'Shorkot': 'Shorkot',
'Sialkot': 'Sialkot',
'Toba Tek Singh': 'Toba Tek Singh',
'Vehari': 'Vehari',
'Wah Cantonment': 'Wah Cantonment',
'Wazirabad': 'Wazirabad',
'Badin': 'Badin',
'Bhan Saeedabad': 'Bhan Saeedabad',
'Bhiria City': 'Bhiria City',
'Chak': 'Chak',
'Dadu': 'Dadu',
'Daharki': 'Daharki',
'Digri': 'Digri',
'Diplo': 'Diplo',
'Dokri': 'Dokri',
'Gambat': 'Gambat',
'Ghotki': 'Ghotki',
'Hala': 'Hala',
'Hyderabad': 'Hyderabad',
'Islamkot': 'Islamkot',
'Jacobabad': 'Jacobabad',
'Jamshoro': 'Jamshoro',
'Jati': 'Jati',
'Johi': 'Johi',
'Kambar': 'Kambar',
'Kandhkot': 'Kandhkot',
'Karachi': 'Karachi',
'Kashmore': 'Kashmore',
'Khairpur': 'Khairpur',
'Khipro': 'Khipro',
'Kot Diji': 'Kot Diji',
'Kunri': 'Kunri',
'Larkana': 'Larkana',
'Matiari': 'Matiari',
'Matli': 'Matli',
'Mehar': 'Mehar',
'Mithi': 'Mithi',
'Mirpur Bathoro': 'Mirpur Bathoro',
'Mirpur Khas': 'Mirpur Khas',
'Moro': 'Moro',
'Naudero': 'Naudero',
'Nawabshah': 'Nawabshah',
'New Saeedabad': 'New Saeedabad',
'Nooriabad': 'Nooriabad',
'Naushehro Feroze': 'Naushehro Feroze',
'Pano Aqil': 'Pano Aqil',
'Qambar Shahdadkot': 'Qambar Shahdadkot',
'Ratodero': 'Ratodero',
'Rohri': 'Rohri',
'Sakrand': 'Sakrand',
'Sanghar': 'Sanghar',
'Sehwan': 'Sehwan',
'Shahdadkot': 'Shahdadkot',
'Shahdadpur': 'Shahdadpur',
'Shikarpur': 'Shikarpur',
'Sinjhoro': 'Sinjhoro',
'Sobhodero': 'Sobhodero',
'Sukkur': 'Sukkur',
'Tando Adam': 'Tando Adam',
'Tando Allahyar': 'Tando Allahyar',
'Tando Muhammad Khan': 'Tando Muhammad Khan',
'Thatta': 'Thatta',
'Tharparkar': 'Tharparkar',
'Umerkot': 'Umerkot',
'Aalborg': 'Aalborg',
'Aarhus': 'Aarhus',
'Kamalia': 'Kamalia',
'Karachi': 'Karachi',
'Lahore': 'Lahore',

};
const countryList = document.getElementById("countries");

for (let country in cities) {
  let Option = document.createElement("option");
  Option.value = cities[country];
  Option.text = cities[country];

cityInput.addEventListener("input", function () {
    let search = this.value.toLowerCase();

    if (search.length >= 2) {
      countryList.appendChild(Option);
    }
});
}

